### ISSUE TITLE
transition of darkmode is very quick and the nav-bar is under other elements while scrolling

### ISSUE THREAD

**Issue by AryanShinde** [mhmiyazi/Movies-Website#1]
i have made some changes, if want i can push it

**Comment by mhmiyazi** [comment]
> i have made some changes, if want i can push it

Ok. Sure.

**Comment by mhmiyazi** [comment]
Lemme check it.
This issue will be fixed ASAP.
Thanks for your contributing.
Either you can make a push.

**Comment by mhmiyazi** [comment]
> i have made some changes, if want i can push it

Thanks.
The transition problem has been fixed.
transition: 1s ease all;  CSS-3 property has been set to on initiate elements.
